#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#define STRINGIFY(v) #v
#define EVAL_STRINGIFY(v) STRINGIFY(v)
#define CONCAT(a,b) a##b
#define EVAL_CONCAT(a,b) CONCAT(a, b)
#define EVAL(v) v

#define PRODUCT_NAME_RAW Media Player Volume Control
#define PRODUCT_NAME EVAL_STRINGIFY(PRODUCT_NAME_RAW)
#define PRODUCT_NAME_WIDE EVAL_CONCAT(L, PRODUCT_NAME)

#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_PATCH 0005
#if _WIN64
#define VERSION_BITS 64
#else
#define VERSION_BITS 32
#endif
#define VERSION_ARCH VERSION_BITS-bit

#if defined(VERSION_PATCH) && VERSION_PATCH > 0
#define VERSION VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH
#else
#define VERSION VERSION_MAJOR.VERSION_MINOR
#endif

#if NDEBUG
#define VERSION_STRING_RAW VERSION VERSION_ARCH
#else
#define VERSION_STRING_RAW VERSION (Debug build)
#endif
#define VERSION_STRING EVAL_STRINGIFY(VERSION_STRING_RAW)
#define VERSION_STRING_WIDE EVAL_CONCAT(L, VERSION_STRING)

#undef CREATEPROCESS_MANIFEST_RESOURCE_ID
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 2
#define IDI_ICON 101

#define IDR_TRAY_POPUPMENU 110
#define IDM_TRAY_POPUPMENU_TOGGLE 111
#define IDM_TRAY_POPUPMENU_HIDE 112
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTHIDDEN_VISIBLE 113
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTHIDDEN_HIDDEN 114
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTHIDDEN_REMEMBER 115
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTDISABLED_ENABLED 116
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTDISABLED_DISABLED 117
#define IDM_TRAY_POPUPMENU_SETTINGS_STARTDISABLED_REMEMBER 118
#define IDM_TRAY_POPUPMENU_SETTINGS_AUTORUN 119
#define IDM_TRAY_POPUPMENU_EXIT 120

#endif // __RESOURCE_H__
